version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=go_template
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go_template_test

volumes:
  pgdata: